### ISSUE TITLE
Error on initial setup

### ISSUE THREAD

**Issue by sneak-it** [kinsi55/docker_SRCDockS#1]
Hey Kinsi,

I deployed the SRCDS watchdog image, and was starting the download of the csgo ds installation. During the tail end of the initial install/update, a CS:GO update was actually pushed by Valve, and the download presented an error:

```
Update detected for Appid 740(csgo): 13774 => 13775
Failed to check for update of csgo: ReferenceError: appManager is not defined
    at /watchdog/main.js:109:64
    at Array.some (<anonymous>)
    at Object.enqueueUpdate (/watchdog/main.js:109:17)
    at AppManager.updateCheck (/watchdog/main.js:59:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I let the install keep going and went fully hands-off to see what it would do. The install continued after some time, however continues to present this error mid-install several times, and failed to fully install after roughly an hour. I had not spun up a server image yet.

This might be an extreme edge-case due to the circumstances, but I figured it warranted at least reporting. Please let me know if you could use any more information.

Thank you!

**Comment by kinsi55** [comment]
Heh this is actually an issue I had spotted at random checking the code for something else but forgot to push my fix, I'll correct it later today.

**Comment by kinsi55** [comment]
Pushed some changes, you should probably start with a clean repo folder, I have no idea how the code was even supposed to properly work the way it was built before.
